name: mlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - conda=4.5.12=py36_1000
  - cython=0.29.2=py36hfc679d8_0
  - pip=18.1=py36_1000
  - numpy=1.15.4=py36_blas_openblashb06ca3d_0
  - pip:
    - autopep8==1.3.5
    - statsmodels==0.9.0
    - scikit-learn==0.20.1
    - matplotlib==2.2.3
    - pandas==0.22.0
    - setuptools==40.6.3
    - wheel==0.32.3
    - python-dateutil==2.7.5
    - -e .
